### ISSUE TITLE
FineOffset

### ISSUE THREAD

**Issue by martin-Stv** [hucknz/cumulusmx#1]
Hi

I have a fine offset station and it connects via USB, I have been on this for 2 days trying to figure out how to connect my Synology USB ports to the container, I would be grateful if you have any ideas

Regards

**Comment by hucknz** [comment]
I believe Synology has limitations around USB devices being passed through to Docker. I don't have one myself so I can't be of much help but this talks about about a workaround: https://mariushosting.com/synology-how-to-add-usb-support-on-dsm-7/
